export const USER = {
    SET_USER_INFO: 'SET_USER_INFO',
    UNSET_USER_INFO: 'UNSET_USER_INFO',
}

export const PROJECTS = {
    SET_PROJECT_LIST: 'SET_PROJECT_LIST',
}

export const ISSUES = {
    SET_ISSUES_LIST: 'SET_ISSUES_LIST',
}